### ISSUE TITLE
Auto close brackets pairs

### ISSUE THREAD

**Issue by gegoune** [nvim-lua/wishlist#11]
**What?**
Modern, working out of the box but configurable auto pair plugin written in lua.

**Why?**
There is popular demand for auto pair close plugins, which is reflected by number of existing solutions. Many of which are outdated, not maintained or simply buggy. It would be nice to have modern, working out of the box solution for neovim.

**Potential existing implementations:**
https://github.com/cohama/lexima.vim
https://github.com/jiangmiao/auto-pairs
https://github.com/rstacruz/vim-closer
https://github.com/Raimondi/delimitMate

https://www.reddit.com/r/vim/comments/6h0dy7/

**Potential pitfalls*:*
Would like it to work with existing lua plugins out of the box. It potentially needs to remap `<CR>` which also plugins like `completion-vim` do (I believe).

**Comment by gegoune** [comment]
https://github.com/windwp/nvim-autopairs

**Comment by matu3ba** [comment]
> https://github.com/windwp/nvim-autopairs

I think the autopair solution should support treesitter for no false bracket creations. It could possibly reuse parts of rainbow.

**Comment by tomtomjhj** [comment]
Another plugin: https://github.com/tmsvg/pear-tree/
This one does a fairly good job at deciding when it's correct to insert/delete matching brackets. [Example](https://github.com/tmsvg/pear-tree#smart-pairing)

**Comment by gegoune** [comment]
@tomtomjhj But that's not lua plugin.

**Comment by bluz71** [comment]
Looks like there is a new option available [pears.nvim](https://github.com/steelsojka/pears.nvim) from @steelsojka.

I don't know how it compares with [nvim-autopairs](https://github.com/windwp/nvim-autopairs).

I currently use [pear-tree](https://github.com/tmsvg/pear-tree) which works quite well. But I do want to give the new Lua alternatives a test drive eventually.

**Comment by windwp** [comment]
latest update of nvim-autopairs added support treesitter and multiple chars.

a new api with rule make it is easy to customize.

**Comment by bluz71** [comment]
And initial endwise infrastructure was also added to nvim-autopairs, which should prove very useful.

**Comment by gegoune** [comment]
That wish seems to be granted.
