### ISSUE TITLE
Fern file type icon support with nvim-web-devicons

### ISSUE THREAD

**Issue by notchtc** [nvim-lua/wishlist#12]
**What?**
File type icons for fern.

**Why?**
There are a few plugins that use [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons/), but fern supports only [vim-devicons](https://github.com/ryanoasis/vim-devicons/) ([fern-renderer-devicons.vim](https://github.com/lambdalisue/fern-renderer-devicons.vim)) and [nerdfont.vim](https://github.com/lambdalisue/nerdfont.vim) ([fern-renderer-nerdfont.vim](https://github.com/lambdalisue/fern-renderer-nerdfont.vim)) and it's kinda stupid to have two plugins that do the same thing just to have icons in fern and in my bar (vim-devicons and nvim-web-devicons).

**Potential existing implementations:**
https://github.com/lambdalisue/fern-renderer-devicons.vim

**Potential pitfalls*:*
¯\_(ツ)_/¯

**Comment by wbthomason** [comment]
This might have more success as an issue on https://github.com/lambdalisue/fern.vim, for what it's worth. It sounds like you want `fern` to add support for `nvim-web-devicons`, rather than wishing for a new plugin, correct?

**Comment by notchtc** [comment]
Well icon support for fern is a separate plugin, even though it's made by the same person that made fern. So support should be a new plugin.

**Comment by lambdalisue** [comment]
Related: https://github.com/lambdalisue/fern-renderer-nerdfont.vim/issues/7

**Comment by notchtc** [comment]
Closing this as this issue is basically dead and I no longer use icons and fern. If someone wants to use fern with nvim-web-devicons there is an alternative to fern called [nvim-tree.lua](https://github.com/kyazdani42/nvim-tree.lua) that uses nvim-web-devicons for icons (it's even made by the same person that made nvim-web-devicons).
