### ISSUE TITLE
Search and replace across multiply files

### ISSUE THREAD

**Issue by Shatur** [nvim-lua/wishlist#18]
**What?**
VSCode have a very convinient way to replace string across multiply files:
![image](https://user-images.githubusercontent.com/22453358/113196803-90e54580-926c-11eb-9d65-7ea91ce61742.png)
In this menu, you can filter found by a specific file type, delete unsuitable entries and replace. And all this in real time with a preview of the result.

**Why?**
In Neovim, you can use Telescope / FZF / grep + Quickfix window + Cfilter. But this approach have some limitations:

1. You cannot replace strings while preserving case. (e.g. replace `FOO` with `BAR` and `foo` with `bar`)
1. There is no convinient way to remove a specific file from the search (which, for example, in the middle), but to apply all other changes.
1. There is no live preview:
![image](https://user-images.githubusercontent.com/22453358/113356834-96658d00-934b-11eb-9b82-eeea0a80dc9e.png)
1. There is no search history in Telescope / FZF (but will be added in Telescope with [this](https://github.com/nvim-telescope/telescope.nvim/pull/521) PR).

So, it would be awesome to a more convinient solution.

**Potential existing implementations:**
Unfortunately, I do not know of any similar plugin, neither in VimScript nor in Lua.

**Comment by RRethy** [comment]
This can be done with the quickfix list, `:grep`, and the standard plugin `cfilter` (bundled with Neovim).

**Comment by Shatur** [comment]
> This can be done with the quickfix list, :grep, and the standard plugin cfilter (bundled with Neovim).

Of course, that's exactly what I meant (just forgot to mention `cfilter`). But this method is not very convenient. In VSCode I can do the same with live preview and much faster.

**Comment by ThePrimeagen** [comment]
So there are plenty of options here to do this.

1.  You need a set of items that are the things you wish to replace.  vimgrep, FzF, or Telescope can all do this.
2.  You pipe them to a quickfix list.  For telescope its C-q, I think its A-tab in FzF (i don't use), and vimgrep goes directly to QF list
3.  Use `cdo`.  cdo can even do confirm.
  

Example)  Here is the things to do.
I have Telescope hooked up and I search for `PerformanceHand`.
![Selection_121](https://user-images.githubusercontent.com/4458174/113338169-f7f31080-92e5-11eb-826e-a743cba79be3.png)

Results Are presented
![Selection_122](https://user-images.githubusercontent.com/4458174/113338166-f75a7a00-92e5-11eb-967e-27ec0a72b58f.png)

Press C-q to pipe to QF list
![Selection_123](https://user-images.githubusercontent.com/4458174/113338161-f75a7a00-92e5-11eb-9930-08d7f40f6489.png)

CDO
![Selection_124](https://user-images.githubusercontent.com/4458174/113338159-f6c1e380-92e5-11eb-8e47-ec163392c81c.png)

Accepting Each Change (drop the c to not do that)
![Selection_125](https://user-images.githubusercontent.com/4458174/113338157-f6294d00-92e5-11eb-8c30-e7960e4a88fc.png)

### Confused about QuickFix Lists and You wish to see a shameless Self Promo?
#### Here is a video on QF lists.
[More Shameless Than Telescopic Johnson](https://www.youtube.com/watch?v=IoyW8XYGqjM)

**Comment by Shatur** [comment]
> You need a set of items that are the things you wish to replace. vimgrep, FzF, or Telescope can all do this.
> You pipe them to a quickfix list. For telescope its C-q, I think its A-tab in FzF (i don't use), and vimgrep goes directly to QF list
> Use cdo. cdo can even do confirm.

This is the way I mentioned in the issue message.
At the moment, I use exactly the same approach to replace things ​​in files in Neovim. I also want to mention the very handy [quickfix-reflector.vim](https://github.com/stefandtw/quickfix-reflector.vim) plugin that allows me to edit things inside Quickfix and write to files on save.

But such approach have some limitations:

1. You cannot replace strings while preserving case. (e.g. replace `FOO` with `BAR` and `foo` with `bar`)
1. There is no convinient way to remove a specific file from the search (which, for example, in the middle), but to apply all other changes.
1. There is no live preview:
![image](https://user-images.githubusercontent.com/22453358/113356834-96658d00-934b-11eb-9b82-eeea0a80dc9e.png)
1. There is no search history in Telescope / FZF (but will be added in Telescope with [this](https://github.com/nvim-telescope/telescope.nvim/pull/521) PR).

Perhaps I should have mentioned this right away. Updated the first post.

So, of course you can do anything in Vim without plugins, but sometimes they make life easier. Therefore, I proposed the idea of ​​a plugin.

**Comment by RRethy** [comment]
1. https://github.com/tpope/vim-abolish
2. There are multiple options, you can use cfilter or just exclude that file as an option to the `:grep` command
3. fzf and telescope no?
4. `<c-j>/<c-k>` in fzf?

**Comment by Shatur** [comment]
1. How can I use it with `cfdo`?
1. You are right, but for CFilter I need to copy filename and add exact match (not very convinient). Also yes, I can exclude it from grep, but not from FZF / Telescope.
2. No, FZF / Telescope will show found occurences, I'm talking about replace preview.
3. Thanks, didn't know about it.

**Comment by RRethy** [comment]
1. You can do a `:cfdo %S/original/replacement/g`.

**Comment by Shatur** [comment]
> You can do a :cfdo %S/original/replacement/g.

Didn't know it works this way. Thank you!
Preserving case was most important to me. Perhaps I will just add custom keybindings for CFilter and will continue to replace strings in this way.

**Comment by RRethy** [comment]
https://github.com/windwp/nvim-spectre

This just got posted to r/neovim and might be closer to vscode experience.

**Comment by Shatur** [comment]
> https://github.com/windwp/nvim-spectre

Looks interesting, will try it out, thanks!

**Comment by dudicoco** [comment]
Is there a way to use the search term input from telescope's `live_grep` within the quickfix list?
I would like to set up a keymap which will open `cdo` with the search term within a search replace statement:
```
cdo s/<live_grep_input>//gc
```
