### ISSUE TITLE
Snippets!

### ISSUE THREAD

**Issue by clason** [nvim-lua/wishlist#2]
**What?**
What it says on the tin: a pure Lua snippet engine.

**Why?**
The major snippet plugins (UltiSnips, neosnippets) are remote python plugins, which adds a dependency. There's also https://github.com/hrsh7th/vim-vsnip in pure vimscript, though, but Lua should have significantly better performance and be more hackable. It should support the basic features: snippet management (either in its own format, UltiSnip/neosnippet format, or LSP); snippet expansion (including nested placeholders) and ideally transformation.

**Potential existing implementations:**
https://github.com/norcalli/snippets.nvim, which is useable but still lacks a few of the above features.

**Potential pitfalls*:*
Ideally, the expansion should be based on extmarks, but that requires the PR https://github.com/neovim/neovim/pull/12249/files to be merged first.

**Comment by clason** [comment]
I think snippets.nvim deserves being moved to the "In Progress" tab :)

**Comment by wbthomason** [comment]
Good point; I've updated the state of all the ideas for which we had a documented partial/in-progress implementation.

**Comment by clason** [comment]
Actually, `snippets.nvim` is arguably full-featured enough now to merit being put into the "Done" category 👍 

(Otherwise it'd be worth specifying what precisely counts as a "Done" plugin...)

**Comment by smolck** [comment]
> (Otherwise it'd be worth specifying what precisely counts as a "Done" plugin...)

That should probably be done regardless, right?

**Comment by wbthomason** [comment]
Yeah, that's a good idea. I'd suggest something like "A wish is 'granted' when there exists a feature-complete, stable plugin implementing the wish's idea". `snippets.nvim` calls itself beta-quality software, so it's not clear that it would meet the "stable" criterion there, but in practice it has seemed stable and feature-complete.

Does that seem reasonable?

**Comment by clason** [comment]
Yeah, that makes sense. (The readme isn't up-to-date, but @norcalli called it basically done on Gitter today.)

**Comment by runiq** [comment]
It has a [wiki](https://github.com/norcalli/snippets.nvim/wiki) now, too.
