### ISSUE TITLE
A plugin which enables preview of s/earch/replace in real-time

### ISSUE THREAD

**Issue by AckslD** [nvim-lua/wishlist#22]
**What?**
A plugin which enables preview of s/earch/replace in real-time.

**Why?**
Something like [traces.vim](https://github.com/markonm/traces.vim) but in lua.

**Potential existing implementations:**
[traces.vim](https://github.com/markonm/traces.vim)

**Potential pitfalls*:*

**Comment by khaveesh** [comment]
`:h inccommand`

**Comment by AckslD** [comment]
@khaveesh Wow, did not know that thanks!
