### ISSUE TITLE
A version of SplitJoin that works with treesitter

### ISSUE THREAD

**Issue by LandonSchropp** [nvim-lua/wishlist#30]
**What?**

I love the [splitjoin.vim](https://github.com/AndrewRadev/splitjoin.vim) plugin. It's been part of my daily workflow for years. However, there are times when it doesn't get things quite right, resulting in syntax errors. I'd love to see a new Neovim version of this plugin that uses treesitter for better accuracy.

**Why?**

This plugin saves a ton of time for daily development, making it easy to extend code to multiple lines or condense it to one line.

**Potential existing implementations:**

[splitjoin.vim](https://github.com/AndrewRadev/splitjoin.vim) is already really solid. However, I think it could be better with treesitter.

**Potential pitfalls*:*

One of the time-consuming aspects of the original splitjoin is working around individual language issues. Hopefully, treesitter would solve those problems.

**Comment by matu3ba** [comment]
I really like the plugin. ThePrimeagen streams his work (on twitch) on refactor.nvim which goes into the same direction https://github.com/ThePrimeagen/refactoring.nvim and is based on the Refactoring book by Martin Fowler. Treesitter included.

**Comment by kylechui** [comment]
A bit late, but I've been using this for a while and have no complaints:
https://github.com/AckslD/nvim-trevJ.lua

**Comment by ObserverOfTime** [comment]
`trevJ` is fine for splitting lines but it can't join them.

Sure, I can use <kbd>va}J</kbd>, for example, but what if I don't want the spaces?
No, <kbd>gJ</kbd> doesn't work since it doesn't remove the existing spaces.

**Comment by Wansmer** [comment]
Hello. I wrote a similar plugin using trееsitter. At the moment, it is not a complete replacement for splitjoin.vim (for example, there is no arrow function conversion in it), but in my cases it's work good.
https://github.com/Wansmer/treesj

**Comment by searleser97** [comment]
> Hello. I wrote a similar plugin using trееsitter. At the moment, it is not a complete replacement for splitjoin.vim (for example, there is no arrow function conversion in it), but in my cases it's work good. https://github.com/Wansmer/treesj

This work should be enough too close this issue I believe

**Comment by LandonSchropp** [comment]
@searleser97 I agree. treesj is awesome!
