### ISSUE TITLE
Help via readme.md

### ISSUE THREAD

**Issue by maxfl** [nvim-lua/wishlist#34]
**What?**
A command `Helpmd <pluginname>` that opens plugin's readme file. Completions provided.

It may find it oin `rtp`or use Packer to get list of paths/

**Why?**
A lot of new plugins do not provide vim help. Nevertheless most of them do provide an informative readme. Currently I have to open the browser to get it. Actually the readme files are provided with plugins so they may be accessed from neovim with a help-like command.

**Potential existing implementations:**
I have not found any.

**Comment by Anrock** [comment]
Hm, that should be easy to implement.

**Comment by matu3ba** [comment]
There is an [open telescope-project PR](https://github.com/nvim-telescope/telescope-project.nvim/pull/67) open for this, but its unfinished (only permanent setting instead of user configurable/keytoggle).
If anyone wants to reuse code from that.

**Comment by maxfl** [comment]
> There is an [open telescope-project PR](https://github.com/nvim-telescope/telescope-project.nvim/pull/67) open for this, but its unfinished (only permanent setting instead of user configurable/keytoggle). If anyone wants to reuse code from that.

I'm using the telescope - great plugin. Can't wait for this being implemented. 

Thank you!

**Comment by fmbarina** [comment]
I ended up giving this idea a shot. 

Mind you, it's likely kind of rough due to my lack of experience developing Neovim plugins, but it works.

- Autocompletion
- Fuzzy searching
- A very bare-bones telescope extension

Maybe [check it out](https://github.com/fmbarina/helpmd.nvim) sometime, if it interests you.

**Comment by maxfl** [comment]
as the packer is no longer supported I've moved to [lazy.nvim](https://github.com/folke/lazy.nvim) and found out it converts readme.md into vimdoc. Great plugin.

**Comment by fmbarina** [comment]
Oh wow, I use lazy too and didn't even know of this feature haha. That's awesome, thanks.

Edit: wait, maybe I'd be good to close this issue then? As I see it, lazy.nvim fulfills the request.

**Comment by maxfl** [comment]
Makes sense, as I do not see any other interested people.
