### ISSUE TITLE
A Lua implementation of Emmet

### ISSUE THREAD

**Issue by Penaz91** [nvim-lua/wishlist#46]
**What?**
An alternative implementation of the Emmet (https:///emmet.io) Domain-specific language.

Is source code is available here: https://github.com/emmetio/emmet

**Why?**
Emmet seems to be a nice way to quickly write chunks of HTML using a short domain-specific language pattern that can be "expanded".

There are some implementations out there but they seem to have been kept unmaintained for some time and their compatibility with existing plugins is unknown.

**Potential existing implementations:**
There are some implementations available:

https://github.com/mattn/emmet-vim

There are also integrations with some completion engines, like nvim-compe and ultisnips:

https://github.com/thendo-rambane/emmet-compe

https://github.com/adriaanzon/vim-emmet-ultisnips

https://github.com/jceb/emmet.snippets

**Potential pitfalls**:
Compatibility with available snippet engines and possible interactions, implementing the logic in lua (if we don't want to just call emmet itself as a kind-of-remote plugin)

**Comment by selectgender** [comment]
I think the Mason plugin has an language server included named emmet-ls
I've had a pretty accurate experience to the original emmet when using it, you should try it out sometime!

**Comment by Penaz91** [comment]
That works great! Thank you for letting me know of that, it perfectly fits my setup, since I already use LSP!
