### ISSUE TITLE
Question: README or issues?

### ISSUE THREAD

**Issue by wbthomason** [nvim-lua/wishlist#5]
@tjdevries @clason @others: I'm debating whether the (original) README-based list of plugin ideas is better or not compared to using issues to track ideas and keeping only information on contributing/a list of "granted wishes" in the README.

The benefit of using issues seems to be easier discussion, tracking if someone has started working on an idea, etc. The downside is mostly that it's harder to discover ideas in issues than if they're all listed in the README.

Of course, I could just keep issues open and link to them in the README, but that seems a little gross in terms of keeping the two in sync.

What do people think about these options?

**Comment by clason** [comment]
@wbthomason Why not just make this a Wiki page on the nvim-lua repo (if that's possible)?

Having the main information in issues seems a bit weird, to be honest, but the approach of just linking from the README to the issues is feasible. An alternative would be the Projects pane.

Another thing would be Github Discussions (similar to StackOverflow, its "issues" which you can vote on and sort, I think).

**Comment by wbthomason** [comment]
@tjdevries had mentioned Github Discussions, which I hadn't heard of - it looks like that's currently in limited beta?

I like the idea of the Projects pane, but I think I prefer it on this repo rather than the organization - I think a repo like this is slightly more discoverable. I'll update the README accordingly and move the existing items to Projects.

Thanks!

**Comment by wbthomason** [comment]
Discussions might be better once it's available, though, since it seems to have a better voting mechanism than issues do.

**Comment by clason** [comment]
@wbthomason yes, that's the point. I recall someone on Gitter mentioning that they had an in on the limited beta? (@mfussenegger, I believe)
