### ISSUE TITLE
Quick actions menu

### ISSUE THREAD

**Issue by f-person** [nvim-lua/wishlist#8]
**What?**
Menu with options that provides refactoring actions from language server.

**Why?**
The UX is great, something like this saves time when refactoring code (probably not in all languages/frameworks, but this is very useful when working  with Flutter).

**Potential existing implementations:**
The only one I know is [coc-actions](https://github.com/iamcco/coc-actions). I still use it, did not stop using CoC for Flutter only for this functionality.

**Comment by p00f** [comment]
>(probably not in all languages/frameworks, but this is very useful when working with Flutter).

also helps in organising imports, generating constructors/equals()/hashCode() in java

**Comment by weilbith** [comment]
At the moment the LSP action callback uses the `inputlist()` function. This is also used for `:tselect` etc. I think this "menu" is horrible. Unfortunately not possible to solve via a plugin, but would be great if this could be tackled in more general.

**Comment by weilbith** [comment]
The plugin [actionmenu.nvim](https://github.com/kizza/actionmenu.nvim) looks pretty good. Also it is not feature complete for this wish here...

**Comment by tricktux** [comment]
Another potential implementation: [nvim-lsputils](https://github.com/RishabhRD/nvim-lsputils)

**Comment by f-person** [comment]
nvim-lsputils is awesome, it has some more cool features like better go to references UX. Wish granted!
